### ISSUE TITLE
Wrapped links are invalid

### ISSUE THREAD

**Issue by EricAndrechek** [b3nj5m1n/xdg-ninja#36] opened 2022-05-16 18:54 UTC
Hi! When my terminal width is too narrow, text automatically wraps which ends up breaking long links. Below is a screenshot:
![image](https://user-images.githubusercontent.com/35144594/168661607-b27346fa-6033-4a4f-88a1-9b706f33fe26.png)

This means that only the first line of the hyperlink is active: https://github.com/ValveSoftware/steam-for- which gives a 404, obviously. I have attempted to read through glow's documentation and issues for anyone referencing this issue but have found no such mention of it.

Additionally, I notice that with glow, the markdown fails to make the text an actual hyperlink, instead just coloring it and underlining it. 

Using escape sequences, it is possible to do this in terminal: 
![image](https://user-images.githubusercontent.com/35144594/168662084-b55e53ef-39a4-495b-a036-8e6d1c8c3288.png)

This acts as a valid hyperlink, and is additionally immune to this sort of text wrapping issue, as demonstrated here:
![image](https://user-images.githubusercontent.com/35144594/168662334-5e2aa621-9a0a-4d91-bffc-afb42d4ac80f.png)

Not sure if this would best be solved with code changes to this repo, or if this may be better targeted towards glow. 

Thanks!

**Comment by EricAndrechek** [comment] 2022-05-16 19:27
I have [created an issue](https://github.com/charmbracelet/glow/issues/344) within the glow repository after doing some additional testing. It appears to be a bug within glow, not this program. The solution I have proposed here and in the glow issue should resolve things. If glow takes too long to fix this, it could potentially be implemented as a hacky fix within this program until glow fixes it on their end.

**Comment by b3nj5m1n** [comment] 2022-05-16 20:13
This is definitely an issue with glow.

I don't think I want to implement a fix here, it's outside the scope of this project. I'll keep up with the issue in glow.

If you can find a maintainable solution for this repo, I'd be more than happy to look at a PR, though.

Thank you for bringing this to my attention.

**Comment by b3nj5m1n** [comment] 2022-05-16 20:47
Upon closer inspection, this doesn't seem to be an issue with glow, you should be able to configure this.

You can invoke glow with the -s flag and provide a custom style definition in json, see [this](https://github.com/charmbracelet/glamour/tree/master/styles#inline-elements) page for details. I think using the prefix, suffix, and block_prefix/block_suffix, you should be able to wrap links in this escape sequence.

I'm sceptical about whether we should use that as a default, though, since not many terminal emulators seem to actually support this escape sequence.

[Here](https://github.com/alacritty/alacritty/pull/5480)'s the relevant PR for alacritty, for example.

If you're interested, you could see if you manage to create a style definition for this, it shouldn't be that hard, afterwards, we could think about trying to detect that ability, but I don't want to add much complexity to this script, so I can't promise anything about merging such functionality.

**Comment by Ballasi** [comment] 2022-05-16 23:22
Isn't this related to the terminal's capability to create links automatically from text?

I cannot reproduce this on `alacritty` or `gnome-terminal`. What terminal are you using @EricAndrechek?

**Comment by b3nj5m1n** [comment] 2022-05-16 23:41
> I'm sceptical about whether we should use that as a default, though, since not many terminal emulators seem to actually support this escape sequence.

That's what I was talking about. You can reproduce their issue using kitty though.

**Comment by EricAndrechek** [comment] 2022-05-17 15:47
> Upon closer inspection, this doesn't seem to be an issue with glow, you should be able to configure this.

I say it is an issue with glow, as I believe it should do that for you. When I write `[a link](https://example.com)` in markdown "[a link](https://example.com)", it creates a hyperlink. I don't have to specify line breaks or anything, it sorts that out for me. If the link wraps to a new line, the whole thing is still valid, it doesn't separate the URL onto two different lines making both lines invalid. 

> Isn't this related to the terminal's capability to create links automatically from text?

As to this comment, I don't believe so, no. In my testing with gnome-terminal, running 
```bash
echo "https://example.com/really-long-link-to-test-a-line-break-that-is-well-over-the-default-80-character-line-length-to-force-the-terminal-to-automatically-wrap-this-text"
```
will automatically wrap as handled by the terminal, and is still a valid and clickable link, as shown below.


![image](https://user-images.githubusercontent.com/35144594/168849792-9e1d525b-0315-4694-8af7-6b2494ddc091.png)

Glow/glamour handles rendering the markdown differently than expected, however. The markdown is not turned into a hyperlink within the terminal, which I understand as it means that even if your terminal doesn't support the [special hyperlink escape sequences](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda#the-escape-sequence) it can still identify the full link to automatically turn it into a clickable link, or allow you to copy and paste it into a web browser. Here is an illustration of the differences I am talking about:
![image](https://user-images.githubusercontent.com/35144594/168851587-76e2e4ea-d0b5-4a38-8340-4944fd1cfd17.png)

IMO, the first hyperlink option is easily the cleanest, but I understand that it may not work on every terminal. The second option clearly works as an alternative, which is fine. The problem arises with the third method. Glow [identifies that the terminal width](https://github.com/charmbracelet/glow/blob/b36e5ad810b6ef9ee3b32869d2af5d7ce461c2fc/main.go#L163) is 80 and manually tells the text to wrap, instead of letting the terminal handle it. This breaks the link. If I tell glow to ignore the terminal width and use a wrap length longer than the link, the terminal wraps it automatically and the link still works.

**Comment by EricAndrechek** [comment] 2022-05-17 17:19
Ok - follow up here. I attempted to using the styling json for glamour/glow to make the hyperlinking work, but unfortunately the order glamour puts them in is incorrect for what the hyperlink expects, and without making modifications to glow this seems impossible. My json was as follows:
```json
{
    "link": {
        "block_prefix": "\\033\\\\",
        "block_suffix": "\\033]8;;\\033\\\\\n"
    },
    "link_text": {
        "block_prefix": "\\033]8;;"
    }
}
```
But unfortunately, glow doesn't actually listen to the escape sequences:
![image](https://user-images.githubusercontent.com/35144594/168870980-3ba46b47-fa9d-41bb-8480-df4fbf63ff6d.png)

Wrapping the whole thing inside an echo will have it listen to the escape sequences and render correctly: 
![image](https://user-images.githubusercontent.com/35144594/168871093-37c69d1c-55b1-4f79-8caa-749ddcec06b8.png)

But as you can see, the link and the link_text are flipped. This is not the way the terminal hyperlink expects it. Again, not an easy fix to this other than modifying glamour's code. Luckily, there seem to already be some people aware of this and working on it: [Glamour: Feature: Support 'modern' anchors through ANSI OSC 8 escapes](https://github.com/charmbracelet/glamour/issues/114), and [Github CLI: Auto-detected links with new lines result in 404s when clicked](https://github.com/cli/cli/issues/3718)

**Comment by b3nj5m1n** [comment] 2022-05-17 17:23
Thanks for your research!

As it's not an issue with this project, I'll close this issue.

**Closed by b3nj5m1n** 2022-05-17 17:23 UTC
Labels: wontfix
